### ISSUE TITLE
Design and Implement Project Database

### ISSUE THREAD

**Issue by MasterEchez** [dhmit/self-sustaining-cities#1]
We will design and implement a database for the project using DjangoDB models which will have many-to-many relationships for people, places, and events for our maps and timeline. It will be accessed by API to make it easier to get from the backend.

Minimum Viable Product:
- a database implemented with Django DB models, which contains dummy data for different people, places, events
- use [this django extension](https://django-extensions.readthedocs.io/en/latest/graph_models.html) to create an easily viewable version of the database schema
- An API where users will be able to:
    - see list of people and single person
    - see list of events and single event
    - see list of places and single place
    - get census JSON data with specified year

Stretch Goals:
- add real data to the database that could be used to present accurate information on the frontend portion of the application

**Comment by anastasia** [comment]
MVP: For visualizing your db schema, please use https://django-extensions.readthedocs.io/en/latest/graph_models.html
Django extension installation instructions: https://django-extensions.readthedocs.io/en/latest/installation_instructions.html
You'll also need the pygraphviz package
```pip install pygraphviz```
Then:
```./manage.py graph_models --pygraphviz -a -g -o my_project_visualized.png``` and you've got your visualization :-)

**Comment by anastasia** [comment]
Let's add some API endpoints to the MVP. 
- Able to see list of people and single person
- Able to see list of events and single event
- Able to see list of places and single place

Let's also get some API endpoints for statistics:
- Able to get census JSON data with specified year

How does that sound? We can talk about API design soon!

**Comment by MasterEchez** [comment]
Sounds good, I will update the original comment.

**Comment by anastasia** [comment]
🚀
