### ISSUE TITLE
Interactive Map Software Development

### ISSUE THREAD

**Issue by leanneshen** [dhmit/self-sustaining-cities#2]
We will create a map interface for users that provides both geographic and historical information about a selected location. 

Minimum Viable Product:
- uses Leaflet.js to create an interactive web-based map
- census tracts are outlined by polygons on the map
- mousing over certain areas triggers popups and sidebars

Stretch goals:
- integrating both chronological and geographical information
- expand the interactive area of the map with consistent information
- get overall city census data
- Be able to switch between city and tract levels
- show data side-by-side

**Comment by anastasia** [comment]
Looks great! Let's add to the stretch goals getting overall city census data, being able to switch between city and single tract information. The afternoon mapping team is working on "specified pins referring to different events on the timeline," so I think we can remove that. Another stretch goal would be showing data side-by-side (this is less a map task and more presenting tabular information, most likely).

**Comment by anastasia** [comment]
🚀
