### ISSUE TITLE
Map Behavior on Click

### ISSUE THREAD

**Issue by kmorhun** [dhmit/self-sustaining-cities#31]
When the user clicks on a marker or a region on the map, it will react by displaying information pulled from the database about the object in question and the region's demographics data, respectively. 

Minimum Viable Product:
- [ ] When the user clicks on a marker on the map, a popup will display the information stored in the database about that person or location in a digestible manner

Stretch Goals:
- [ ] Write a component for each kind of data that may be displayed in a marker popup 

Possibilities (If we find this necessary, depending on our research and the amount of census data that we have)
- [ ] When the user clicks on a region on the map, it will trigger a display of the demographics data associated with it

**Comment by anastasia** [comment]
Looks great!
