### ISSUE TITLE
Census Data Visualization

### ISSUE THREAD

**Issue by pauladc** [dhmit/self-sustaining-cities#32]
**Description:**
We will be creating a visualization of 1940 census data from the Deanwood neighborhood, Washington D.C. Our task will be two-fold: 1) processing the census data, selecting and reorganizing the attributes that are relevant; 2) displaying the data in multiple visual forms, including a heat map for demographic information, pie chart, line graph, etc.

**Minimum viable product:**

- [ ] Process the census data, selecting and reorganizing relevant attributes.
- [ ] Input the data into the backend.
- [ ] Display data in a clear table format, and adjust columns to have consistent units/scaling.
- [ ] Create a heat map to display demographic data.
- [ ] Create alternate forms of visualizations, such as a pie chart to visualize demographic data.

**Extended features (stretch goals):**

- [ ] Add a search function to easily find categories.
- [ ] Add a filtering function that will allow the user to easily view data of interest.
- [ ] Allow scalability for census data from different years and different locations.
- [ ] Create line graphs to visualize how data changes across years.

**Comment by anastasia** [comment]
For the MVP, let's use dummy data or the data that is there right now. Take a look at the census data as reference, but no need to first ingest the data before you start trying out different visualizations. For visualizations, you should check out ChartJS https://github.com/reactchartjs/react-chartjs-2 https://medium.com/@vickdayaram/using-chart-js-with-react-324b7fac8ee6
