### ISSUE TITLE
Map Key

### ISSUE THREAD

**Issue by nfrieden** [dhmit/self-sustaining-cities#33]
We will be building a map key that displays different information associated with different parts of the map. The keys will display different types of data, i.e. addresses, census data, according to a specific identifying factor like color.

**Minimum Viable Product** 

- [ ] Key formatted in a corner of the map (bottom left)
- [ ] Key originally filled with placeholder data (not pulled in from the backend yet)
- [ ] On click, placeholder key displays information related to topic
- [ ] Preferably, key is made through leaflet methods (since the component uses leaflet.js)

**Extended Features** 

- [ ] Keys filled with values pulled from the backend (data dependent)
- [ ] If key reaches certain size, only display a few (and/or create a drop-down menu with the rest)
- [ ] Create support for a heat map (maybe for census data?)
- [ ] Re-sizable key?

The basic version would look something like this: 

![mapkey_figma](https://user-images.githubusercontent.com/95311896/153961754-fbb1181f-f764-47ae-bf32-e3989df4c2c5.png)

**Comment by anastasia** [comment]
Looks great!
