### ISSUE TITLE
Interactive Timeline 

### ISSUE THREAD

**Issue by angcast** [dhmit/self-sustaining-cities#4]
We will be building a timeline interface that showcases documents with key historic events that are shared through transcribed articles. In our project, documents are papers that have 1 or more articles. Meanwhile, articles are what make up a document.

**Minimum Viable Product**:
- [x] Display a timeline with each of the documents
- [x] When you click on the document, show a modal with the date, title, and a zoom out/in feature for the document. 
- [x] Show a slideshow of the individual articles if the document contains multiple
- [x] Panning document
- [x] Being able to click timeline intervals
- [x] Both scrolling and left/right arrows to change year intervals

**Extended Features (Stretch Goals)**:
- [x] Tagging feature where you could add tags to documents
- [x] Filter and sort tools for the timeline: 
    - [x] Sort chronologically, most recent
    - [ ] Filter through tags 
- [x] Being able to click specific timeline years
    - [ ] Blur out documents that aren't from the specific year (think about the case where there’s no documents)

![Full Screen Pop Up](https://user-images.githubusercontent.com/39710446/149416862-2692ee0f-8e3c-4d2c-941b-88d6f4f5efba.png)

@anastasia @ryaanahmed

**Comment by anastasia** [comment]
This is fantastic! Thank you for including the mock-up as well. It's very clear where this is headed, great work.

**Comment by anastasia** [comment]
OOPS! This got auto-closed with the PR.

**Comment by anastasia** [comment]
🚀
